// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpihqLuV21atUoap0-4YNu44ZwmGuBFL8',
    appId: '1:912335026632:web:a979d55c25869c36a568fd',
    messagingSenderId: '912335026632',
    projectId: 'chat-eduardo-firabase',
    authDomain: 'chat-eduardo-firabase.firebaseapp.com',
    storageBucket: 'chat-eduardo-firabase.firebasestorage.app',
    measurementId: 'G-6ML0NX0DDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2t7yUr8OocJUfxqWEN_Mm4tZ19ZZVT8',
    appId: '1:912335026632:android:15a6866fc1a727aca568fd',
    messagingSenderId: '912335026632',
    projectId: 'chat-eduardo-firabase',
    storageBucket: 'chat-eduardo-firabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewaMX9NGHb6brXx0YnLTnxFPPFGaWapI',
    appId: '1:912335026632:ios:495ad0f8dc59151aa568fd',
    messagingSenderId: '912335026632',
    projectId: 'chat-eduardo-firabase',
    storageBucket: 'chat-eduardo-firabase.firebasestorage.app',
    iosBundleId: 'com.eduardoand.chatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewaMX9NGHb6brXx0YnLTnxFPPFGaWapI',
    appId: '1:912335026632:ios:495ad0f8dc59151aa568fd',
    messagingSenderId: '912335026632',
    projectId: 'chat-eduardo-firabase',
    storageBucket: 'chat-eduardo-firabase.firebasestorage.app',
    iosBundleId: 'com.eduardoand.chatapp.chatapp',
  );
}
